### ISSUE TITLE
검색창 화면 구성하기

### ISSUE THREAD

**Issue by blueline1984** [pre-onboarding-team10/pre-onboarding-10th-2-10#1]
- [ ] 질환명 검색시 **API 호출** 통해서 검색어 추천 기능 구현
- [ ] input onChange 시 추천 검색어 창에 “**검색어 없음**” 표출
- [ ] 키보드만으로 추천 검색어들로 이동 가능하도록 구현하기

**Comment by AEJIJEON** [comment]
#5 
- 의도에 맞는 기능 구현
- 컴포넌트 역할이 명확하게 드러나도록 네이밍, props구성
- 컴포넌트, 훅 관심사에 맞게 분리

**Comment by JunJongHun** [comment]
#5 

- 코드 가독성
- 컴포넌트 분리
- 확장성

**Comment by jeongminsang** [comment]
#5 

- 컴포넌트 관심사 분리
- 명확한 구현 상태

현재 프록시 설정이 안되어있는것 같은데, 과제가 cors를 우회해서 진행하라고 하니 수정하실때 프록시 설정을 해주시면 좋을 것 같습니다.

**Comment by yan9vvoojin** [comment]
#5

- 가독성
- 관심사 분리
- 기능 완성도

**Comment by 04ian80** [comment]
#10 
- 커스텀 훅으로 관리하여 가독성 좋음
- 관심사가 심플하게 분리되어있음

**Comment by rabbit-22** [comment]
#12

- 가독성 있는 코드
- 명확한 관심사 분리
- 코드 확장성
- 적절한 네이밍

**Comment by woongsnote** [comment]
#12 
- 간결한 코드
- 적절한 네이밍
- 코드 확장성

**Comment by hyukzz** [comment]
#10

- 구조 파악이 쉽다.
- 추후 기능 붙이기 쉬울 것 같다.

**Comment by hyukzz** [comment]
> #5 
> 
> 
> 
> - 컴포넌트 관심사 분리
> 
> - 명확한 구현 상태
> 
> 
> 
> 현재 프록시 설정이 안되어있는것 같은데, 과제가 cors를 우회해서 진행하라고 하니 수정하실때 프록시 설정을 해주시면 좋을 것 같습니다.
-> 저는 크롬 익스텐션에 cors우회해주는 걸 켜놔서 따로 설정 안 했습니다. Allow CORS일거에요. 서버가 추후에도 해결안되면 추가하겠습니다!

**Comment by blueline1984** [comment]
#9
- 전반적으로 코드가 정돈되어 가독성이 좋음
- 상수처리 등 많은 부분 신경쓴 부분이 보임
