### ISSUE TITLE
로컬 캐싱 구현하기

### ISSUE THREAD

**Issue by blueline1984** [pre-onboarding-team10/pre-onboarding-10th-2-10#2]
- [ ] 캐싱 구현
- [ ] expire time 구현
- [ ] 입력마다 API 호출하지 않도록 API 호출 횟수를 줄이는 기능 구현
- [ ] API를 호출할 때 마다 `console.info("calling api")` 출력

**Comment by yan9vvoojin** [comment]
#21

- API 호출 시에만 디바운스를 적용한 아이디어
- 가독성 있고 이해하기 쉬운 코드

**Comment by woongsnote** [comment]
#21 

- API 호출 시에만 디바운스를 적용한 아이디어
- 만료된 cache clear
- 가독성 있고 이해하기 쉬운 코드

**Comment by JunJongHun** [comment]
#21 
- api 호출시에만 디바운스 적용 아이디어 굿

**Comment by jeongminsang** [comment]
#21
- 시간 상수 처리
- api 호출시에만 디바운스 적용
- 깔끔한 구현상태

**Comment by 04ian80** [comment]
#20 
- 상황 고려하여 그에 맞는 스토리지 사용
- cache 관련 함수는 apiClient에서 처리하였고, 그 안에서도 api와 cache를 분리하여 작성. 가독성 좋음
- debounce 함수 가독성 좋음. debounce 함수는 다른 함수나 변수의 의존성없이 debounce만을 처리하고, debounce 적용도 깔끔.

**Comment by rabbit-22** [comment]
#20

- 클래스를 활용하여 추상화
- debounce를 분리하여 확장성 높은 코드 작성

**Comment by AEJIJEON** [comment]
#20 

- 상황 고려하여 그에 맞는 스토리지 사용
- 가독성, 확장성 고려하여 캐싱 기능 구현
- 별도의 debounce util 함수를 사용하여 정확한 기능 구현

**Comment by blueline1984** [comment]
고민이 되었지만...ㅠㅠ

#20
- 명확한 기준을 통해 스토리지 선택한 점!

**Comment by hyukzz** [comment]
#20 

storage 방법이 가장 적합해서 뽑았습니다.
