### ISSUE TITLE
UI 작업 및 리드미 작성

### ISSUE THREAD

**Issue by blueline1984** [pre-onboarding-team10/pre-onboarding-10th-2-10#4]
- [ ] UI 작업
- [ ] 리드미 작성

**Comment by woongsnote** [comment]
#25 
- 가독성 좋음
- 디자인 깔끔함

**Comment by JunJongHun** [comment]
#29 
- 디자인 디테일 작업 부분 좋았다
- 자주쓰는 스타일 변수화 시킨거 좋았다
- 반응형 고려한 점 굿이였다

**Comment by jeongminsang** [comment]
#26 
- 가장 유사한 디자인
- SVG를 사용한 icon
- 깔끔한 코드

**Comment by AEJIJEON** [comment]
#29 
- 반응형 고려
- 깔끔한 css 파일 분리

**Comment by rabbit-22** [comment]
#27

- 유사한 디자인
- 디테일한 부분 리팩토링

**Comment by yan9vvoojin** [comment]
#29

- 반응형 디자인
- 자주 쓰는 스타일 변수화

**Comment by blueline1984** [comment]
#29 

- 반응형
- 파일 분리

**Comment by hyukzz** [comment]
#29 

- 반응형 작업
- 홈페이지에서 7개씩 검색어를 보여주는데 이 부분 추가해주시면 좋지 않을까 싶습니다 ㅎㅎ

**Comment by 04ian80** [comment]
#25 
- 홈페이지와 거의 똑같은 깔끔한 UI
- 컴포넌트 폴더화
